quolance-api/.gitignore
quolance-api/.mvn/wrapper/maven-wrapper.properties
quolance-api/mvnw
quolance-api/mvnw.cmd
quolance-api/pom.xml
quolance-api/src/main/java/com/quolance/quolance_api/QuolanceApiApplication.java
quolance-api/src/main/java/com/quolance/quolance_api/configs/ApplicationConfiguration.java
quolance-api/src/main/java/com/quolance/quolance_api/configs/JwtAuthenticationFilter.java
quolance-api/src/main/java/com/quolance/quolance_api/configs/SecurityConfiguration.java
quolance-api/src/main/java/com/quolance/quolance_api/configs/SwaggerConfig.java
quolance-api/src/main/java/com/quolance/quolance_api/controllers/AuthenticationController.java
quolance-api/src/main/java/com/quolance/quolance_api/dtos/LoginResponseDto.java
quolance-api/src/main/java/com/quolance/quolance_api/dtos/UserDto.java
quolance-api/src/main/java/com/quolance/quolance_api/dtos/UserLoginDto.java
quolance-api/src/main/java/com/quolance/quolance_api/dtos/UserRegistrationDto.java
quolance-api/src/main/java/com/quolance/quolance_api/entities/AbstractEntity.java
quolance-api/src/main/java/com/quolance/quolance_api/entities/User.java
quolance-api/src/main/java/com/quolance/quolance_api/entities/enums/Role.java
quolance-api/src/main/java/com/quolance/quolance_api/entities/enums/UserType.java
quolance-api/src/main/java/com/quolance/quolance_api/exceptions/GlobalExceptionHandler.java
quolance-api/src/main/java/com/quolance/quolance_api/repositories/UserRepository.java
quolance-api/src/main/java/com/quolance/quolance_api/services/AuthenticationService.java
quolance-api/src/main/java/com/quolance/quolance_api/services/UserService.java
quolance-api/src/main/java/com/quolance/quolance_api/services/UserServiceImpl.java
quolance-api/src/main/java/com/quolance/quolance_api/services/auth/AuthenticationServiceImpl.java
quolance-api/src/main/java/com/quolance/quolance_api/services/auth/JwtService.java
quolance-api/src/main/java/com/quolance/quolance_api/services/impl/UserServiceImpl.java
quolance-api/src/main/resources/application.properties
quolance-api/src/test/java/com/quolance/quolance_api/QuolanceApiApplicationTests.java

- Backend project setup
- User authentication and authorization #3 
- User registration #2

2-3 user registration and authentication backend

---

.github/workflows/main.yml

Build and test frontend
Build and test backend
Frontend tests are commented for now, uncomment when there are tests that are pushed for frontend

Added yml file for the cicd pipeline

---

quolance-api/src/main/java/com/quolance/quolance_api/configs/SecurityConfiguration.java
quolance-api/src/main/java/com/quolance/quolance_api/controllers/ClientController.java
quolance-api/src/main/java/com/quolance/quolance_api/dtos/ProjectDto.java
quolance-api/src/main/java/com/quolance/quolance_api/dtos/UserDto.java
quolance-api/src/main/java/com/quolance/quolance_api/entities/AbstractEntity.java
quolance-api/src/main/java/com/quolance/quolance_api/entities/Project.java
quolance-api/src/main/java/com/quolance/quolance_api/entities/User.java
quolance-api/src/main/java/com/quolance/quolance_api/repositories/ProjectRepository.java
quolance-api/src/main/java/com/quolance/quolance_api/repositories/UserRepository.java
quolance-api/src/main/java/com/quolance/quolance_api/services/ClientService.java
quolance-api/src/main/java/com/quolance/quolance_api/services/ProjectService.java
quolance-api/src/main/java/com/quolance/quolance_api/services/UserService.java
quolance-api/src/main/java/com/quolance/quolance_api/services/impl/ClientServiceImpl.java
quolance-api/src/main/java/com/quolance/quolance_api/services/impl/ProjectServiceImpl.java
quolance-api/src/main/java/com/quolance/quolance_api/services/impl/UserServiceImpl.java

feat: Client can post a project #4 #18
implemented Client controller, client service, project service

BE client can post a project

---

quolance-ui/src/app/(with-main-layout)/layout.tsx
quolance-ui/src/app/(with-main-layout)/projects/page.tsx
quolance-ui/src/app/layout.tsx
quolance-ui/src/app/page.tsx
quolance-ui/src/components/global/BreadCrumb.tsx
quolance-ui/src/components/global/Header.tsx
quolance-ui/src/components/global/MobileMenu.tsx
quolance-ui/src/components/ui/Pagination.tsx
quolance-ui/src/components/ui/ProjectCard.tsx
quolance-ui/src/data/data.ts
quolance-ui/src/hooks/useScroll.tsx
quolance-ui/src/hooks/useToggle.tsx

Freelancers can view list of projects #7 #23
- Added a header to navigate to home and projects page ( mobile responsive)
- Added a projects page. It has a simple filter and pagination functionality.
-  The projects can be filtered by date posted and by status.
-  The projects are static and stored in a file called data under data folder.
-  Added a Hero section to home page so its not blank

Added UI for freelancers to view and filter through projects

---

quolance-ui/src/app/(with-main-layout)/freelancer-apply/[id]/page.tsx
quolance-ui/src/app/(with-main-layout)/projects/page.tsx
quolance-ui/src/components/ui/ProjectCard.tsx
quolance-ui/src/data/data.ts

- First concept of the UI for freelancer proposal (static)
#5 
#24

Freelancer can submit a proposal for a project #5 Parent: #24

---

Quolance API.postman_collection.json

Added postman collection as a file, since Postman allows teams of no more than 3 people on the free plan.

added postman collection

---

quolance-api/src/main/java/com/quolance/quolance_api/configs/SecurityConfiguration.java
quolance-api/src/main/java/com/quolance/quolance_api/configs/SwaggerConfig.java

Added ability to use jwt based authentication on swagger, can be an alternative to postman

#3 added bearer option on swagger

---

QuolanceAPI.postman_collection.json
quolance-api/src/main/java/com/quolance/quolance_api/dtos/ProjectDto.java
quolance-api/src/main/java/com/quolance/quolance_api/entities/Project.java
quolance-api/src/main/java/com/quolance/quolance_api/entities/enums/ExpectedDeliveryTime.java
quolance-api/src/main/java/com/quolance/quolance_api/entities/enums/FreelancerExperienceLevel.java
quolance-api/src/main/java/com/quolance/quolance_api/entities/enums/PriceRange.java
quolance-api/src/main/java/com/quolance/quolance_api/entities/enums/ProjectCategory.java

Added missing fields to Project entity 

---

quolance-api/src/main/java/com/quolance/quolance_api/controllers/FreelancerController.java
quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/ApplicationProcessWorkflow.java
quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/ApplicationProcessWorkflowImpl.java

feat: (BE-136) Freelancer can cancel (remove) his application

---

QuolanceAPI.postman_collection.json
quolance-api/src/main/java/com/quolance/quolance_api/configs/SecurityConfiguration.java
quolance-api/src/main/java/com/quolance/quolance_api/controllers/ClientController.java
quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/ApplicationProcessWorkflow.java
quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/ApplicationProcessWorkflowImpl.java
quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/ApplicationServiceImpl.java

feat: (BE-134) Client can reject 1 or many applicant

---

QuolanceAPI.postman_collection.json
quolance-api/src/main/java/com/quolance/quolance_api/configs/SecurityConfiguration.java
quolance-api/src/main/java/com/quolance/quolance_api/controllers/PendingController.java
quolance-api/src/main/java/com/quolance/quolance_api/dtos/UpdatePendingUserRequestDto.java
quolance-api/src/main/java/com/quolance/quolance_api/entities/User.java
quolance-api/src/main/java/com/quolance/quolance_api/entities/enums/Role.java
quolance-api/src/main/java/com/quolance/quolance_api/jobs/SendTempPasswordEmailJob.java
quolance-api/src/main/java/com/quolance/quolance_api/jobs/handlers/SendTempPasswordEmailJobHandler.java
quolance-api/src/main/java/com/quolance/quolance_api/services/auth/PendingWorkflowService.java
quolance-api/src/main/java/com/quolance/quolance_api/services/auth/impl/OAuth2LoginSuccessHandlerImpl.java
quolance-api/src/main/java/com/quolance/quolance_api/services/auth/impl/PendingWorkflowServiceImpl.java
quolance-api/src/main/java/com/quolance/quolance_api/util/validators/PasswordMatchValidator.java
quolance-api/src/main/resources/mail-templates/generated-password-email.html
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/components/pending-user-form.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/components/update-password-and-role-form.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/layout.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/profile/page.tsx
quolance-ui/src/constants/models/user/UserResponse.ts

---
This pull request introduces a seamless and secure registration flow for OAuth2 users, addressing the specific needs of users who register via external authentication providers like Google or GitHub.
Key changes include:
- A new `PENDING` role for handling OAuth2 user registration.
- Sending temporary passwords via email to OAuth2 users.
- Backend and frontend support for completing registration through password updates and role selection.
- Asynchronous email processing for scalability.
---
- **Commit:** [`#139 Allowed user creation from Selected Auth Provider`](https://github.com/ChemsCode/commit/a50bcad)
- Modified the `Oauth2LoginSuccessHandler` to allow user creation with default handling for OAuth2 users.
- Ensures that OAuth2 users receive a temporary password to complete their …

[#139] Comprehensive OAuth2 User Registration Flow Implementation

---

quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/ApplicationProcessWorkflowImpl.java

Changed application statuses for non-selected applications to REJECTED.
Closes #170

Added rejection for unselected freelancers

---

quolance-api/src/main/java/com/quolance/quolance_api/controllers/FreelancerController.java
quolance-api/src/test/java/com/quolance/quolance_api/helpers/EntityCreationHelper.java
quolance-api/src/test/java/com/quolance/quolance_api/integration/AbstractTestcontainers.java
quolance-api/src/test/java/com/quolance/quolance_api/integration/ClientControllerIntegrationTest.java
quolance-api/src/test/java/com/quolance/quolance_api/integration/FreelancerControllerIntegrationTest.java
quolance-api/src/test/java/com/quolance/quolance_api/integration/Helper.java

- Added new integration test class.
- Extracted the handling of the testcontainer to an abstract class.
- Extracted helper functions to a new class for creation of entities.
**Note: `deleteApplication` is not used anywhere, to be deleted**

test: Integration tests for FreelancerController operations for #169

---

quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/ProjectServiceImpl.java
quolance-api/src/test/java/com/quolance/quolance_api/helpers/EntityCreationHelper.java
quolance-api/src/test/java/com/quolance/quolance_api/integration/AdminControllerIntegrationTest.java
quolance-api/src/test/java/com/quolance/quolance_api/integration/ClientControllerIntegrationTest.java
quolance-api/src/test/java/com/quolance/quolance_api/integration/FreelancerControllerIntegrationTest.java

- Added integration tests for the admin controller

test: Integration tests for AdminController operations for #169

---

quolance-api/src/main/java/com/quolance/quolance_api/services/auth/impl/AuthServiceImpl.java
quolance-api/src/test/java/com/quolance/quolance_api/integration/AuthControllerIntegrationTest.java

test: Integration tests for AuthController operations for #169

---

quolance-api/src/main/java/com/quolance/quolance_api/controllers/FreelancerController.java
quolance-api/src/test/java/com/quolance/quolance_api/unit/AdminControllerUnitTest.java
quolance-api/src/test/java/com/quolance/quolance_api/unit/AuthControllerUnitTest.java
quolance-api/src/test/java/com/quolance/quolance_api/unit/ClientControllerUnitTest.java
quolance-api/src/test/java/com/quolance/quolance_api/unit/FreelancerControllerUnitTest.java

Added unit tests for Admin, Auth, Client and Freelancer Controllers #116

test: Added unit tests for Admin, Auth, Client and Freelancer Controllers

---

quolance-api/src/test/java/com/quolance/quolance_api/unit/jobs/SendResetPasswordEmailUnitTest.java
quolance-api/src/test/java/com/quolance/quolance_api/unit/jobs/SendTempPasswordEmailUnitTest.java
quolance-api/src/test/java/com/quolance/quolance_api/unit/jobs/SendWelcomeEmailUnitTest.java

Implemented unit tests for jobs

---

quolance-api/src/main/java/com/quolance/quolance_api/services/auth/impl/AuthServiceImpl.java
quolance-api/src/test/java/com/quolance/quolance_api/integration/AuthControllerIntegrationTest.java

Changed error code and message

bugfix: fixed error code for unregistered email login for #185

---

quolance-ui/src/api/auth-api.ts
quolance-ui/src/app/(without-main-layout)/auth/login/components/user-auth-form.tsx
quolance-ui/src/app/(without-main-layout)/auth/login/page.tsx
quolance-ui/src/app/(without-main-layout)/auth/register/components/AuthHeader.tsx
quolance-ui/src/app/(without-main-layout)/auth/register/components/RadioCardUser.tsx
quolance-ui/src/app/(without-main-layout)/auth/register/components/register-form.tsx
quolance-ui/src/app/(without-main-layout)/auth/register/page.tsx
quolance-ui/src/app/(without-main-layout)/auth/shared/auth-components.tsx
quolance-ui/src/components/ui/button.tsx

This PR introduces significant reworks and enhancements to the authentication-related components in the Quolance UI:
1. **Registration Form Rework**:
- Introduced new `RadioCardUser` components for selecting user roles (client or freelancer) during registration.
- Simplified and enhanced the registration form layout and logic with reusable components (`FormInput`, `SocialAuthLogins`).
2. **Login Form Updates**:
- Refactored the login form to use shared components (`FormInput`, `SocialAuthLogins`).
- Addid loading state handling when logging in with `isLoginLoading` in `auth-api.ts`.
3. **Added Header for Auth Pages**:
- Implemented a new `AuthHeader` component to provide consistent navigation and context for the authentication pages.
4. **User Role Selection UI**:
- Added a card-based UI …

feat: Rework frontend registration flow for #176

---

quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/whats-new/blog/page.tsx
quolance-ui/src/components/ui/blog/BlogContainer.tsx
quolance-ui/src/components/ui/blog/PostCard.tsx
quolance-ui/src/components/ui/blog/SearchBar.tsx
quolance-ui/src/components/ui/blog/Tabs.tsx

---
This PR implements the post viewing and the dynamic tab-based filtering system for blog posts. It allows users to filter posts by tags, dynamically add new tabs, and highlights the currently selected tab. Additionally, it introduces improved post display and interaction functionalities to enhance the user experience.
---
- Added a dynamic `Tabs` component to allow users to filter posts based on tags.
- Enabled automatic tag extraction from posts to populate the default tabs.
- Implemented custom tab creation functionality with proper validation.
- Highlighted the currently selected tab with distinct styling.
- Introduced a filtering mechanism to ensure only posts matching the selected tab's tag are displayed.
- Added a fallback message when no posts match the selected filter.
- The …

feat: Make UI for viewing blog posts for #124

---

QuolanceAPI.postman_collection.json
quolance-api/src/main/java/com/quolance/quolance_api/controllers/FreelancerController.java
quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/FreelancerWorkflowService.java
quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/FreelancerWorkflowServiceImpl.java
quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/UserService.java
quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/UserServiceImpl.java

https://res.cloudinary.com/dt1m5nygt/image/upload/v1735691292/images/hyvqwc2sihcoxpsd7g2l.png

feat: A freelancer can Upload a Profile picture and View it in his profile for #224

---

QuolanceAPI.postman_collection.json
quolance-api/src/main/java/com/quolance/quolance_api/configs/AdminInitializer.java
quolance-api/src/main/java/com/quolance/quolance_api/controllers/ClientController.java
quolance-api/src/main/java/com/quolance/quolance_api/controllers/FreelancerController.java
quolance-api/src/main/java/com/quolance/quolance_api/controllers/PublicController.java
quolance-api/src/main/java/com/quolance/quolance_api/controllers/WebSocketController.java
quolance-api/src/main/java/com/quolance/quolance_api/dtos/CreateAdminRequestDto.java
quolance-api/src/main/java/com/quolance/quolance_api/dtos/CreateUserRequestDto.java
quolance-api/src/main/java/com/quolance/quolance_api/dtos/LoginRequestDto.java
quolance-api/src/main/java/com/quolance/quolance_api/dtos/UpdateUserRequestDto.java
quolance-api/src/main/java/com/quolance/quolance_api/dtos/UserResponseDto.java
quolance-api/src/main/java/com/quolance/quolance_api/dtos/profile/FreelancerProfileDto.java
quolance-api/src/main/java/com/quolance/quolance_api/entities/User.java
quolance-api/src/main/java/com/quolance/quolance_api/repositories/UserRepository.java
quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/ClientWorkflowService.java
quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/FreelancerWorkflowService.java
quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/ClientWorkflowServiceImpl.java
quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/FreelancerWorkflowServiceImpl.java
quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/UserService.java
quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/UserServiceImpl.java
quolance-api/src/test/java/com/quolance/quolance_api/helpers/EntityCreationHelper.java
quolance-api/src/test/java/com/quolance/quolance_api/integration/ClientControllerIntegrationTest.java
quolance-api/src/test/java/com/quolance/quolance_api/integration/FreelancerControllerIntegrationTest.java
quolance-api/src/test/java/com/quolance/quolance_api/integration/UsersControllerIntegrationTest.java
quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/UsersControllerUnitTest.java
quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/UserServiceUnitTest.java

feat: BE-224 User can have a username that is used to view a freelancer profile

---

quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/UserServiceImpl.java

bugfix: Refined welcome email thrown exception fix

---

QuolanceAPI.postman_collection.json
quolance-api/src/main/java/com/quolance/quolance_api/controllers/AdminController.java
quolance-api/src/main/java/com/quolance/quolance_api/controllers/FreelancerController.java
quolance-api/src/main/java/com/quolance/quolance_api/controllers/PublicController.java
quolance-api/src/main/java/com/quolance/quolance_api/dtos/project/ProjectFilterDto.java
quolance-api/src/main/java/com/quolance/quolance_api/repositories/ProjectRepository.java
quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/AdminWorkflowService.java
quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/FreelancerWorkflowService.java
quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/AdminWorkflowServiceImpl.java
quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/FreelancerWorkflowServiceImpl.java
quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/ProjectService.java
quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/ProjectServiceImpl.java
quolance-api/src/test/java/com/quolance/quolance_api/integration/AdminControllerIntegrationTest.java
quolance-api/src/test/java/com/quolance/quolance_api/integration/FreelancerControllerIntegrationTest.java
quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/AdminControllerUnitTest.java
quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/FreelancerControllerUnitTest.java
quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/PublicControllerUnitTest.java
quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/AdminWorkflowServiceUnitTest.java
quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/FreelancerWorkflowServiceUnitTest.java
quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/ProjectServiceUnitTest.java

This PR implements filtering capabilities for the projects list with pagination support to improve performance and user experience.
- Add filter endpoints for projects with query parameter support
- Implement pagination logic with configurable page size
- Add sorting capabilities for project results
- Include response metadata for total count and page information
Closes #230

Implement project filtering with pagination support

---

quolance-ui/src/app/(with-main-layout)/projects/[id]/FreelancerApplicationForm.tsx
quolance-ui/src/app/(with-main-layout)/projects/[id]/ProjectSubmissions.tsx
quolance-ui/src/app/(with-main-layout)/projects/[id]/page.tsx
quolance-ui/src/app/(without-main-layout)/(authenticated-pages)/(client-protected-pages)/post-project/page.tsx
quolance-ui/src/components/postProjectSteps/StepFour.tsx
quolance-ui/src/components/ui/freelancers/FreelancerCard.tsx
quolance-ui/src/components/ui/projects/ProjectCard.tsx
quolance-ui/src/components/ui/projects/ProjectDetailsHeader.tsx
quolance-ui/src/constants/models/applications/ApplicationResponse.ts
quolance-ui/src/constants/models/user/UserResponse.ts
quolance-ui/src/util/stringUtils.ts

This PR addresses several issues related to project status consistency and application management, particularly focusing on closed projects and freelancer interactions.
* Fixed inconsistency where closed projects were showing as active in project listing
* Removed status indicators in ProjectCard component
* Restricted new applications for closed projects
* Added clear status messaging when projects are no longer accepting applications
* Enhanced FreelancerCard component with improved status handling
* Added dedicated UI component for closed project states
* Removed mock data dependencies
* Added proper freelancer profile information display
* Improved submission filtering and status management
* Fixed HTML tags displaying in project review step
* Added RichTextDisplay component …

fix: Fixed UI defects in the app for #226

---

QuolanceAPI.postman_collection.json

Updated JSOn with new endpoints for comment functionality.

Refactor: Update QuolanceAPI.postman_collection.json

---

.github/workflows/main.yml
quolance-ui/cypress.config.ts
quolance-ui/cypress/e2e/admin.cy.ts
quolance-ui/cypress/e2e/login.cy.ts
quolance-ui/cypress/e2e/registration.cy.ts
quolance-ui/cypress/e2e/setting.cy.ts
quolance-ui/cypress/e2e/spec.cy.ts
quolance-ui/cypress/support/commands.ts
quolance-ui/cypress/support/e2e.ts
quolance-ui/cypress/tsconfig.json
quolance-ui/package-lock.json
quolance-ui/package.json
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/adminDashboard/adminApproveProject/page.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/adminDashboard/page.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/componentsAdmin/ConfirmationModal.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/componentsAdmin/CreateAdminForm.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/componentsAdmin/ProjectAdminCard.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/componentsAdmin/ProjectDetails.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/dashboard/ClientDashboardActionButtons.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/dashboard/FreelancerDashboardActionButtons.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/setting/components/ChangePassword.tsx
quolance-ui/src/app/(without-main-layout)/auth/login/components/user-auth-form.tsx
quolance-ui/src/app/(without-main-layout)/auth/register/components/RadioCardUser.tsx
quolance-ui/src/app/(without-main-layout)/auth/register/components/register-form.tsx
quolance-ui/src/app/(without-main-layout)/auth/register/page.tsx
quolance-ui/src/app/(without-main-layout)/auth/shared/auth-components.tsx
quolance-ui/src/components/error-feedback.tsx
quolance-ui/src/components/success-feedback.tsx

This pr does not close the issue #210. This pr is for configuring cypress, adding some e2e tests, and updating the cicd to run these tests. More tests need to be added in the next iteration.
In this iteration, 4 specs were created: Registration, Login, Admin, and Setting, comprising a total of 12 tests.
- Registration Spec: Tests both error and successful registration flows. Error scenarios include cases with missing inputs, mismatched passwords, and duplicate emails.
- Login Spec: Focuses on error and successful login flows. Error cases include missing inputs and invalid credentials, such as incorrect passwords or non-existent emails.
- Admin Spec: Covers error and successful admin creation flows, testing scenarios like missing inputs, mismatched passwords, and duplicate emails. It also …

test: Add frontend tests for #210

---

quolance-api/src/main/java/com/quolance/quolance_api/configs/WebSocketConfig.java
quolance-api/src/main/java/com/quolance/quolance_api/controllers/NotificationRestController.java
quolance-api/src/main/java/com/quolance/quolance_api/controllers/WebSocketController.java
quolance-api/src/main/java/com/quolance/quolance_api/dtos/websocket/NotificationResponseDto.java
quolance-api/src/main/java/com/quolance/quolance_api/dtos/websocket/SendNotificationRequestDto.java
quolance-api/src/main/java/com/quolance/quolance_api/entities/MessageEntity.java
quolance-api/src/main/java/com/quolance/quolance_api/entities/Notification.java
quolance-api/src/main/java/com/quolance/quolance_api/entities/Project.java
quolance-api/src/main/java/com/quolance/quolance_api/entities/enums/MessageType.java
quolance-api/src/main/java/com/quolance/quolance_api/repositories/NotificationRepository.java
quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/FreelancerWorkflowServiceImpl.java
quolance-api/src/main/java/com/quolance/quolance_api/services/websockets/WebSocketService.java
quolance-api/src/main/java/com/quolance/quolance_api/services/websockets/impl/AbstractWebSocketService.java
quolance-api/src/main/java/com/quolance/quolance_api/services/websockets/impl/ChatMessageService.java
quolance-api/src/main/java/com/quolance/quolance_api/services/websockets/impl/GreetingMessageService.java
quolance-api/src/main/java/com/quolance/quolance_api/services/websockets/impl/NotificationMessageService.java
quolance-api/src/main/java/com/quolance/quolance_api/util/validators/PasswordMatch.java
quolance-api/src/main/java/com/quolance/quolance_api/util/websockets/WebSocketServiceLocator.java
quolance-api/src/main/java/com/quolance/quolance_api/util/websockets/WebSocketUtils.java
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/websockettest/page.tsx

---
This merge request introduces critical fixes, enhancements, and refactoring across multiple components of the application. It resolves existing bugs in the WebSocket handling and enhances the Notification system for improved reusability, maintainability, and extensibility.
Key updates include:
1. Fixes for WebSocket-related bugs and session security context issues.
2. Overhaul of WebSocket service handling to adhere to a modular and service-oriented architecture.
3. Integration of a robust notification workflow for triggering notifications via WebSocket.
4. Refinement of various entities, DTOs, controllers, and repositories to support the new workflow seamlessly.
---
- **WebSocket Security Context Issue:**
- Removed HTTP session-related `SecurityContext` in favor of the STOMP context …

feat:  Notification Systems And Comprehensive Enhancements to WebSocket

---

quolance-api/src/main/java/com/quolance/quolance_api/configs/CustomUserDetailsService.java
quolance-api/src/main/java/com/quolance/quolance_api/configs/SecurityConfiguration.java
quolance-api/src/main/java/com/quolance/quolance_api/dtos/LoginRequestDto.java
quolance-api/src/main/java/com/quolance/quolance_api/repositories/UserRepository.java
quolance-api/src/main/java/com/quolance/quolance_api/services/auth/impl/AuthServiceImpl.java
quolance-api/src/test/java/com/quolance/quolance_api/integration/AdminControllerIntegrationTest.java
quolance-api/src/test/java/com/quolance/quolance_api/integration/AuthControllerIntegrationTest.java
quolance-api/src/test/java/com/quolance/quolance_api/integration/BlogCommentControllerIntegrationTest.java
quolance-api/src/test/java/com/quolance/quolance_api/integration/BlogPostControllerIntegrationTest.java
quolance-api/src/test/java/com/quolance/quolance_api/integration/ClientControllerIntegrationTest.java
quolance-api/src/test/java/com/quolance/quolance_api/integration/FreelancerControllerIntegrationTest.java
quolance-api/src/test/java/com/quolance/quolance_api/integration/UsersControllerIntegrationTest.java
quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/AuthControllerUnitTest.java

https://github.com/user-attachments/assets/9eceb618-ac04-4f1c-ad6c-ed90a06f38ea

feat: Users are able to login with both username and email for #235

---

quolance-api/src/test/java/com/quolance/quolance_api/integration/BlogCommentControllerIntegrationTest.java
quolance-ui/src/api/auth-api.ts

Changed payload to allow users to login w/ username

bugfix: Login Fix

---

.github/workflows/main.yml
quolance-api/src/main/java/com/quolance/quolance_api/jobs/handlers/SendWelcomeEmailJobHandler.java
quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/ApplicationServiceImpl.java
quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/FileServiceImpl.java
quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/ProjectServiceImpl.java
quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/UserServiceImpl.java
quolance-api/src/main/resources/application.yml

small snippet of some logs
Need to add the following line to the .env:
`LOG_FILE=./logs/quolance.log`

feat: #262 Added detailed logging info

---

quolance-ui/src/app/(without-main-layout)/auth/login/components/user-auth-form.tsx
quolance-ui/src/app/(without-main-layout)/auth/register/components/AuthHeader.tsx
quolance-ui/src/app/(without-main-layout)/auth/register/components/register-form.tsx
quolance-ui/src/app/(without-main-layout)/auth/register/page.tsx
quolance-ui/src/components/ui/projects/ProjectDetailsHeader.tsx

Fixed labels, and added username field in registration

chore: #294 Fix Project flow and prepare for release

---

quolance-api/src/main/java/com/quolance/quolance_api/controllers/NotificationRestController.java
quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/ClientWorkflowServiceImpl.java
quolance-api/src/main/java/com/quolance/quolance_api/services/websockets/impl/GreetingMessageService.java
quolance-api/src/main/java/com/quolance/quolance_api/services/websockets/impl/NotificationMessageService.java
quolance-api/src/main/java/com/quolance/quolance_api/util/websockets/WebSocketServiceLocator.java

This pull request introduces a centralized mechanism for handling notifications within the application, ensuring clients and freelancers can receive notifications consistently and reliably in-app. The changes improve maintainability, scalability, and usability for various notification workflows.
---
1. **Centralized `processNotification` Method**:
- Introduced a unified method to handle the core logic of saving notifications to the database and broadcasting them via WebSocket.
- Ensures timestamping, persistence, and `NotificationResponseDto` conversion are applied consistently across all workflows.
2. **Enhanced Notification Sending Workflows**:
- **Clients and Freelancers**:
- Notifications can now be sent to individual users, groups of users, or all subscribed users in-app.
- Updated …

feat: #172 Client/freelancer can receive notifications in-app

---

quolance-ui/src/components/ui/blog/BlogContainer.tsx

Fixed an issue where newly created blog posts did not appear immediately after submission. Now, the blog refreshes automatically to display the latest posts.  
---
- **Added Query Invalidation:** Ensures fresh data is fetched after post creation.  
---
✅ **Closes #328**
---
Creating blog post
Blog refreshed without page reloading

bugfix: #328 Blog posts not displayed upon creation

---

.github/workflows/main.yml
quolance-api/src/main/java/com/quolance/quolance_api/dtos/profile/ProfileCompletionCalculator.java
quolance-ui/package-lock.json
quolance-ui/package.json
quolance-ui/src/api/freelancer-api.ts
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/componentsAdmin/ProjectDetails.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/AboutSection.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/AvailabilitySection.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ContactSection.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/EditButton.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ExperienceSection.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProfileHeader.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProfileImageModal.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProfileProgressBar.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProfileStatus.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/SaveButton.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/SkillsSection.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/UpdateProfileModal.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/page.tsx
quolance-ui/src/constants/models/user/UserResponse.ts

This pr is for issue #335 and should close story #333.It implements a progress bar in freelancer profile page, connects the progress bar to the backend, and updates the ui for both profile page and image modal.
- This hook located in freelancer-api.ts is used to fetch current profile percentage from backend
```typescript
export const useGetProfileCompletion = () => {
return useQuery<number>({
queryKey: ['profileCompletion'],
queryFn: async () => {
const response = await httpClient.get('/api/freelancer/profile/completion');
return response.data; 
},
});
};
```
- Contains the bar with the percentage
- Message indicating sections that need to be completed
- A "Don't show again" button that closes the progress bar
- A "Update profile" button that opens up a modal to update profile( other than …

feat: #335 Implement UI for profile completion progress bar

---

.github/workflows/main.yml
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProfileStatus.tsx

Made changes to the ProfileStatus.tsx that was causing ESLint error during npm run build
In the original function of filterMissingFields the let missing variable was causing the error
```typescript
const filterMissingFields = () => {
let missing: string[] = [];
Object.entries(profile).forEach(([key, value]) => {
if (
key !== "id" &&
key !== "userId" &&
key !== "username" &&
(
value === null ||
value === undefined ||
value === "" ||
(Array.isArray(value) &&
(value.length === 0 || value.every((item) => item === "")))
)
) {
missing.push(key);
}
});
const uniqueRecommendations = Array.from(
new Set(missing.map((key) => getRecommendation(key)))
).filter(Boolean) as string[];
setMissingFields(uniqueRecommendations);
};
```
The function was refactored to the following
```typescript
const …
```

bugfix: #361 Frontend fails to build due to ESLint error

---

quolance-ui/src/api/blog-api.ts
quolance-ui/src/components/ui/blog/BlogContainer.tsx
quolance-ui/src/components/ui/blog/PostCard.tsx
quolance-ui/src/constants/models/http/PagedResponse.ts

This PR introduces pagination functionality for both blog posts and comments, allowing users to navigate efficiently through content. The implementation improves performance, user experience, and ensures that only a limited number of posts and comments load at a time. Additionally, TypeScript errors related to paginated responses have been resolved.
---
- Implemented support for **paginated blog post retrieval** via the backend API.  
- Integrated **Next** / **Previous** buttons for easy navigation.  
- Updated UI to display **current page number and total pages dynamically**.  
- Ensured blog posts refresh properly when switching pages.
- **Handled edge cases**:  
- Disabled `Next` button when on the last page.  
- Disabled `Previous` button when on the first page.  
- Implemented …

feat: #327 fe handle paging for comments and posts

---

quolance-api/src/main/java/com/quolance/quolance_api/controllers/ClientController.java
quolance-api/src/main/java/com/quolance/quolance_api/dtos/application/ApplicationCreateDto.java
quolance-api/src/main/java/com/quolance/quolance_api/dtos/application/ApplicationDto.java
quolance-api/src/main/java/com/quolance/quolance_api/dtos/project/ProjectFilterDto.java
quolance-api/src/main/java/com/quolance/quolance_api/entities/Application.java
quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/ClientWorkflowService.java
quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/ClientWorkflowServiceImpl.java
quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/FreelancerWorkflowServiceImpl.java
quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/FreelancerControllerIntegrationTest.java
quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/ClientControllerUnitTest.java
quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/FreelancerControllerUnitTest.java
quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/ClientWorkflowServiceUnitTest.java
quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/FreelancerWorkflowServiceUnitTest.java

This PR address and fixes some filtering and data retrieval functionality in the freelancer and project APIs. These changes improve the accuracy of freelancer searches, project filtering, and application management.
- Addressed additions/fixes mentioned in issue
- Updated Corresponding Tests
- Modified query logic in the freelancer search functionality to use an AND condition when filtering by multiple skills.  
- Implemented missing experience level filtering in the project retrieval API to ensure projects are correctly filtered by experience level.  
- Added a `message` field to the `Applications` table.  
- Updated application creation logic to allow freelancers to submit a custom message with their application.  
- Added `applied` filtering in the Freelancer GetAllProjects for better …

feat: #358 Fix/Add Filtering, Fields in Project and Application in BE

---

quolance-api/src/main/java/com/quolance/quolance_api/controllers/UsersController.java
quolance-api/src/main/java/com/quolance/quolance_api/dtos/users/NotificationSubscriptionResponseDto.java
quolance-api/src/main/java/com/quolance/quolance_api/entities/User.java
quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/UserService.java
quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/UserServiceImpl.java
quolance-api/src/main/java/com/quolance/quolance_api/services/websockets/impl/NotificationMessageService.java
quolance-ui/src/api/notifications-api.ts
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/notifications/page.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/setting/components/NotificationSubscription.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/setting/page.tsx
quolance-ui/src/components/ui/notifications/NotificationPanel.tsx
quolance-ui/src/util/context/webSocketContext.tsx

This PR introduces a fully integrated notification subscription system, improving both backend functionality and frontend user experience.  
- Users can now subscribe/unsubscribe from notifications, with their preferences persisted in the database.  
- WebSocket integration ensures users only receive notifications if they are subscribed.  
- The UI has been redesigned to provide a better experience for managing notifications on both mobile and desktop.  
---
_A short video demonstrating the changes in action can be found here:_  
https://github.com/user-attachments/assets/6ac087f4-fa27-4ba3-95e2-3622ca8abf0c
---
- Added `notificationsSubscribed` field to `User` entity (default `true`).  
- Created DTOs to handle notification subscription preferences.  
- **New API Endpoints in …

feat: #393 Implement Notification Subscription System with UI Enhancements & Backend Fixes**  

---

quolance-api/src/main/java/com/quolance/quolance_api/controllers/blog/BlogCommentController.java
quolance-api/src/main/java/com/quolance/quolance_api/controllers/blog/BlogPostController.java
quolance-api/src/main/java/com/quolance/quolance_api/controllers/blog/ReactionController.java
quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/blog/BlogCommentServiceImpl.java
quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/blog/BlogPostServiceImpl.java
quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/blog/ReactionServiceImpl.java

- Added logging statements for blogpost-related classes: Controllers and service layer for blogPost, blogComment, and Reactions.
- Changed a few methods to make the log statement work with the exception handling.
closes #363

feat: #363 Added logging statements in blog post related classes in BE.

---

.github/workflows/main.yml
quolance-ui/cypress/e2e/admin.cy.ts
quolance-ui/cypress/e2e/client.cy.ts
quolance-ui/cypress/e2e/login.cy.ts
quolance-ui/cypress/e2e/registration.cy.ts
quolance-ui/cypress/e2e/setting.cy.ts
quolance-ui/package.json
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/componentsAdmin/ConfirmationModal.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/componentsAdmin/ProjectDetails.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/dashboard/ClientDashboardActionButtons.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/dashboard/ClientDashboardTable.tsx
quolance-ui/src/components/postProjectSteps/StepOne.tsx
quolance-ui/src/components/ui/freelancers/ApprovalConfirmationModal.tsx
quolance-ui/src/components/ui/freelancers/FreelancerCard.tsx
quolance-ui/src/components/ui/projects/ProjectDetailsHeader.tsx

I updated the current cypress files (admin,login,registration, and setting) by adding more tests. I added a new test file client that tests additional client flow in the application. There are currently 23 total tests. In the remaining iterations more tests will be added to test more functionality. The tests now run in build instead of dev in main.yml
Currently the statement ,branch, function and line coverage are below 80%. These numbers reflect the files the tests cover only and not all files in quolance-ui.As more tests get added and current tests refactored the numbers will go up.

test: #405 adding more cypress tests

---

quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/AboutSection.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/AvailabilitySection.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ExperienceSection.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProfileHeader.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProfileStatus.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/SaveButton.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/SkillsSection.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/UpdateProfileModal.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/page.tsx
quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/why-quolance/reviews/page.tsx
quolance-ui/src/app/globals.css

Fixed swiper overflow page section issue : 
Improved skills section and overall display of the profile page: 
++Fixed bugs in the UI

feat: #371 Improve profile page, and adjust UI pages bugs

---

quolance-api/src/main/java/com/quolance/quolance_api/entities/Profile.java
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/AboutSection.tsx

bugfix: #420 Fixed bug where bios could not be longer than 255 chars and added character counter on bio field in UI

---

QuolanceAPI.postman_collection.json
quolance-api/src/main/java/com/quolance/quolance_api/controllers/chat/ChatController.java
quolance-api/src/main/java/com/quolance/quolance_api/dtos/chat/MessageDto.java
quolance-api/src/main/java/com/quolance/quolance_api/dtos/chat/SendMessageDto.java
quolance-api/src/main/java/com/quolance/quolance_api/entities/User.java
quolance-api/src/main/java/com/quolance/quolance_api/entities/chat/Message.java
quolance-api/src/main/java/com/quolance/quolance_api/repositories/chat/MessageRepository.java
quolance-api/src/main/java/com/quolance/quolance_api/services/chat/ChatService.java
quolance-api/src/main/java/com/quolance/quolance_api/services/chat/impl/ChatServiceImpl.java
quolance-api/src/main/resources/toggles.properties

This PR implements a minimal chat system that allows direct messaging between users on the Quolance platform.
- Create Message entity with sender, receiver, content, and timestamp
- Implement MessageRepository with query to find message history between users
- Add bidirectional relationships between User and Message entities
- Create DTOs for message data transfer
- Implement ChatService interface with basic methods
- Add REST endpoints for sending and retrieving messages
- Configure feature toggle for enabling/disabling chat functionality
- Update Postman collection with chat endpoints for testing
This implementation includes only essential features:
- Direct messaging between users
- Message history retrieval
- Feature toggle for enabling/disabling
Future enhancements could include:
- …

feat: #422 Added basic implementation for chat system

---

quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/BlogCommentControllerUnitTest.java
quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/BlogReactionControllerUnitTests.java
quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/BlogCommentServiceUnitTest.java
quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/ProjectModerationServiceUnitTest.java
quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/ReactionServiceUnitTests.java

- Increased Test coverage by adding Unit Tests for the BlogComment and BlogReaction controllers. 
- Added unit tests for the service implementation layer regarding the BlogComments, BlogReactions and ProjectModeration.
Closes #429

test: #429 Added Unit Tests for the Reaction and Comment controllers as well as the service layers in BE

---

quolance-api/pom.xml
quolance-api/src/main/java/com/quolance/quolance_api/controllers/ChatController.java
quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/AdminWorkflowServiceImpl.java
quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/ApplicationProcessWorkflowImpl.java
quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/ClientWorkflowServiceImpl.java
quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/FreelancerWorkflowServiceImpl.java
quolance-api/src/main/java/com/quolance/quolance_api/services/chat/ChatService.java
quolance-api/src/main/java/com/quolance/quolance_api/services/chat/impl/ChatServiceImpl.java
quolance-api/src/main/java/com/quolance/quolance_api/services/websockets/impl/NotificationMessageService.java
quolance-api/src/test/java/com/quolance/quolance_api/helpers/integration/NoOpNotificationConfig.java
quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/AdminControllerIntegrationTest.java
quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/ClientControllerIntegrationTest.java
quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/FreelancerControllerIntegrationTest.java
quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/UsersControllerIntegrationTest.java
quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/AdminWorkflowServiceUnitTest.java
quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/ApplicationProcessWorkflowUnitTest.java
quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/ClientWorkflowServiceUnitTest.java
quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/FreelancerWorkflowServiceUnitTest.java

#445: Add Notification Integration Across Workflow Service Implementations
This pull request introduces comprehensive notification integration across various workflow service implementations. By injecting and leveraging our centralized `NotificationMessageService`, the application now sends real-time notifications to users during key events across client, freelancer, application process, and admin workflows. These changes enhance user engagement by providing immediate feedback on actions such as project creation, application submission, freelancer selection, and administrative decisions.
1. **ClientWorkflowServiceImpl Enhancements**
- **Project Creation:**  
After a project is successfully created, a notification is sent to the client confirming the project creation.
- **Project Update:** …

feat: #445 Add Notification Integration Across Workflow Service Implementations

---

QuolanceAPI.postman_collection.json
quolance-api/src/main/java/com/quolance/quolance_api/controllers/ChatController.java
quolance-api/src/main/java/com/quolance/quolance_api/dtos/chat/ContactDto.java
quolance-api/src/main/java/com/quolance/quolance_api/repositories/MessageRepository.java
quolance-api/src/main/java/com/quolance/quolance_api/services/chat/ChatService.java
quolance-api/src/main/java/com/quolance/quolance_api/services/chat/impl/ChatServiceImpl.java
quolance-api/src/main/resources/toggles.properties

The new `/api/chat/contacts` endpoint retrieves all users the current authenticated user has communicated with, providing essential information for displaying a contacts list in the chat interface.
- **URL**: `/api/chat/contacts`
- **Method**: GET
- **Authentication**: Required
- **Response Format**: JSON array
Each contact in the response includes:
- `userId`: UUID of the contact user
- `name`: Full name of the contact (first name + last name)
- `profilePicture`: URL to the contact's profile image
- `lastMessage`: Content of the most recent message in the conversation
- `lastMessageTimestamp`: When the last message was sent
- Contacts are automatically sorted by the timestamp of the most recent message (newest first)
- Uses efficient database queries to retrieve contact relationships
- …

feat: #422 added get contacts endpoint

---

quolance-api/src/main/java/com/quolance/quolance_api/dtos/review/ReviewDto.java
quolance-ui/src/api/client-api.ts
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ReviewCard.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/page.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/dashboard/page.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/public-profile/[username]/page.tsx
quolance-ui/src/app/(with-main-layout)/projects/[id]/ProjectSubmissions.tsx
quolance-ui/src/components/ui/freelancers/AddReviewModal.tsx
quolance-ui/src/components/ui/freelancers/FreelancerCard.tsx
quolance-ui/src/constants/models/candidates/CandidateResponse.ts
quolance-ui/src/constants/models/user/UserResponse.ts

The ui was created for posting a review for a freelancer a client worked with. The ui was also created for the review tab in the public profile page of freelancer. Both are connected to the backend. This pr will close #454 #455.
- On the submissions page for the client they will see the following Add Review button in the freelancer card for the freelancer they approved.
- When client clicks on the Add Review button a modal will pop up with the first rating option for delivery time of product. There are 5 options to choose from very poor (1), poor(2), average(3), very good (4), Exceptional (5)
- After clicking next the rating option for communication will appear
- After clicking next the rating option for quality of work will appear
- After clicking next the written review option will …

feat: #455 make UI for client rating on a freelancer profile

---

QuolanceAPI.postman_collection.json
quolance-api/src/main/java/com/quolance/quolance_api/controllers/ChatController.java

This PR removes the logging functionality from the ChatController and updates Postman collection by removing unused pagination parameters from the "Get Messages With User" endpoint.

bugfix: Removed logging from chat system

---

quolance-api/src/main/java/com/quolance/quolance_api/services/auth/impl/PendingWorkflowServiceImpl.java
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/components/update-password-and-role-form.tsx

This pull request addresses several improvements and bug fixes:
- **OAuth2 Freelancer Creation:**  
Handles cases where a Freelancer is created via OAuth2, ensuring proper onboarding and user setup.
- **Orphan Removal Bug Fix:**  
Resolves an issue related to orphan removal in the User entity, ensuring managed collections are maintained correctly without unintended deletions.
- **Frontend Flow Update:**  
Updates the flow from the frontend for a smoother and more intuitive user experience.
Closes #499.

bugfix: #499 Freelancer created with OAuth2 does not have an associated profile

---

quolance-ui/cypress/e2e/registration.cy.ts
quolance-ui/src/app/(without-main-layout)/auth/register/components/PasswordRequirement.tsx
quolance-ui/src/app/(without-main-layout)/auth/register/components/register-form.tsx

This PR introduces real-time password validation feedback to improve the registration experience. As users type their password, a visual checklist displays which strength requirements have been met, guiding them toward creating a secure password.
---
- Implemented a Zod schema with common password strength rules:
- Minimum 8 characters  
- At least one uppercase letter  
- At least one lowercase letter  
- At least one number  
- At least one special character
- Added specific error messages for each rule to improve clarity.
- Created `PasswordRequirements` component:
- Dynamically displays a checklist of password requirements.
- Updates in real-time as the user types.
- Integrated `watch` from `react-hook-form` to track password input
- Imported and rendered the `PasswordRequirements` …

feat: #505 Added Password Requirements on Registration

---

quolance-api/src/main/resources/application.yml
quolance-api/src/main/resources/mail-templates/welcome-email.html
quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/support/faqs/page.tsx
quolance-ui/src/components/home/HeroSection.tsx

- Split the questions in different categories, making it easier for users to find relevant questions.
- Added more questions and answers
- Added clickable section titles
- Reworked the UI to make it more visually appealing
Closes #516

feat: #516 Added questions to FAQ and made it more interactive

---

quolance-api/src/main/java/com/quolance/quolance_api/controllers/AuthController.java
quolance-api/src/main/java/com/quolance/quolance_api/dtos/users/VerifyEmailDto.java
quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/UserService.java
quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/UserServiceImpl.java
quolance-api/src/main/resources/mail-templates/welcome-email.html
quolance-ui/src/app/(without-main-layout)/auth/register/components/register-form.tsx
quolance-ui/src/app/(without-main-layout)/auth/verify-email/[email]/page.tsx
quolance-ui/src/app/(without-main-layout)/auth/verify-email/components/verification-code.tsx
quolance-ui/src/components/verify-account.tsx

- Simplified the email verification process for users. 
- Previously, they needed to input their email in the verification page, now the email is embedded in the redirection url after registration and also in the email they receive.
- Removed the email field from the verification page
- Modified the input for the code
- The submit button is inactive while the user does not put in the 6 characters
Closes #532

feat: #532 Improved the email verification process

---

quolance-ui/src/app/(with-main-layout)/projects/[id]/FreelancerApplicationForm.tsx
quolance-ui/src/components/postProjectSteps/StepFour.tsx

- Made sure the user must acknowledge and agree with the terms of service and that we are not responsible for any problems that may arise. 
Closes #463

feat: #463 Added checkbox to make client remove liability from us when creating a project

---

quolance-ui/src/app/(without-main-layout)/auth/register/page.tsx

removed the 2 repeating "Already have an account?"

bugfix: #463 Removed double account sign in redirect

---

.github/workflows/deploy.yml
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(client-protected-pages)/candidates/CandidatesContainer.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/components/pending-user-form.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/components/update-password-and-role-form.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/dashboard/ClientDashboardActionButtons.tsx
quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/dashboard/page.tsx
quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/how-it-works/find-a-freelancer/page.tsx
quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/how-it-works/find-clients/page.tsx
quolance-ui/src/app/(without-main-layout)/auth/register/components/register-form.tsx
quolance-ui/src/app/(without-main-layout)/auth/register/page.tsx
quolance-ui/src/components/home/HeroSection.tsx

Couple of improvements, and text changes. NON BREAKING CHANGES

Chore : #544 Fix UI display issues, and improvements (NON-BREAKING CHANGES)

---

quolance-ui/src/components/global/MobileMenu.tsx

feat: #546 Added Blog Link to mobile menu

---

README.md

- Added Demo link (the one played in the EV building)
- Added release demo link
- Updated environment variables in the readme
- Edited the table of important tests
- Edited the table of important files

documentation: Updated readme for final release
