abdelh17/Quolance

QuolanceAPI.postman_collection.json, quolance-api/src/main/java/com/quolance/quolance_api/configs/SecurityConfiguration.java, quolance-api/src/main/java/com/quolance/quolance_api/controllers/ClientController.java, quolance-api/src/main/java/com/quolance/quolance_api/controllers/FreelancerController.java, quolance-api/src/main/java/com/quolance/quolance_api/controllers/UsersController.java, quolance-api/src/main/java/com/quolance/quolance_api/dtos/ApplicationDto.java, quolance-api/src/main/java/com/quolance/quolance_api/services/ClientService.java, quolance-api/src/main/java/com/quolance/quolance_api/services/FreelancerService.java, quolance-api/src/main/java/com/quolance/quolance_api/services/ProjectService.java, quolance-api/src/main/java/com/quolance/quolance_api/services/UserService.java, quolance-api/src/main/java/com/quolance/quolance_api/services/impl/ClientServiceImpl.java, quolance-api/src/main/java/com/quolance/quolance_api/services/impl/FreelancerServiceImpl.java, quolance-api/src/main/java/com/quolance/quolance_api/services/impl/ProjectServiceImpl.java, quolance-api/src/main/java/com/quolance/quolance_api/services/impl/UserServiceImpl.java
- Client and freelancer endpoints need authentication, removed from whitelist.
- Requests are made according to the authenticated user, not the id of users in the bodies or parameters of requests.
For example, if a freelancer wants to see all his applications, the id is not passed anywhere, rather we use `SecurityUtil.getAuthenticated()`.
Closes #75
=> 75 improve authorization security

quolance-api/src/main/java/com/quolance/quolance_api/configs/SecurityConfiguration.java, quolance-api/src/main/java/com/quolance/quolance_api/controllers/UsersController.java, quolance-api/src/main/java/com/quolance/quolance_api/dtos/CreateAdminRequestDto.java, quolance-api/src/main/java/com/quolance/quolance_api/entities/User.java, quolance-api/src/main/java/com/quolance/quolance_api/services/UserService.java, quolance-api/src/main/java/com/quolance/quolance_api/services/impl/UserServiceImpl.java, quolance-api/src/main/java/com/quolance/quolance_api/util/SecurityUtil.java
Admin can create admin. To make it work locally, comment out the line:
`.requestMatchers(antMatcher(HttpMethod.POST, "/api/users/admin")).hasRole("ADMIN")` in the `SecurityConfiguration` file., create an admin, then put back the restriction. Make sure you run it on `ddl-auto=update` to not delete the admin
Closes #29
=> 29 BE Admin can create admin

QuolanceAPI.postman_collection.json, quolance-api/src/main/java/com/quolance/quolance_api/configs/SecurityConfiguration.java, quolance-api/src/main/java/com/quolance/quolance_api/controllers/AdminController.java, quolance-api/src/main/java/com/quolance/quolance_api/dtos/ProjectDto.java, quolance-api/src/main/java/com/quolance/quolance_api/dtos/RejectProjectRequestDto.java, quolance-api/src/main/java/com/quolance/quolance_api/entities/Project.java, quolance-api/src/main/java/com/quolance/quolance_api/entities/enums/ProjectStatus.java, quolance-api/src/main/java/com/quolance/quolance_api/repositories/ProjectRepository.java, quolance-api/src/main/java/com/quolance/quolance_api/services/AdminService.java, quolance-api/src/main/java/com/quolance/quolance_api/services/ProjectService.java, quolance-api/src/main/java/com/quolance/quolance_api/services/impl/AdminServiceImpl.java, quolance-api/src/main/java/com/quolance/quolance_api/services/impl/ProjectServiceImpl.java
Added an enum for the project status, and it is set to PENDING upon creation.
Added 3 endpoints for an admin user:
1. Reject a project.
2. Approve a project
3. Get all pending projects
for points 1 and 2 they work only when the status of a project is PENDING, but will need to be changed later to accommodate for rejecting an existing project, or approving a project rejected by the AI model.
Closes #33
=> 33 Admin can approve/reject a pending project

quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/adminDashboard/adminCreateAdmin/page.tsx, quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/adminDashboard/page.tsx, quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/componentsAdmin/CreateAdminForm.tsx
Created the UI and connected it to the backend for admin create admin #10 #56 
The adminDashboard page now has a create admin option
Once you click on it you are navigated to the adminCreateAdmin page which has a form.
If you enter incorrect credentials for email and password errors will appear in red on the form. If there are no errors a success  toast will appear and admin will be navigated to the dashboard page.
=> 56 fe make UI for admin creates admin

.github/workflows/main-branch-analysis.yml, .github/workflows/main.yml, quolance-api/pom.xml, quolance-ui/sonar-project.properties
- Added SonarCloud scan in the pipeline whenever a PR is made. 
- Automates the scans that were previously manually ran locally.
- Will allow us to fix code defects and improve the quality of the code
- Added the version of the jacoco maven plugin because to address warning messages in previous builds.
- 2 scans are executed: 1 for frontend, 1 for backend.
- In SonarCloud, they are setup as 2 projects within a monorepo.
- Backend: [Backend scan](https://sonarcloud.io/summary/new_code?id=abdelh17_Quolance_api)
- Frontend: [Frontend scan](https://sonarcloud.io/project/overview?id=abdelh17_Quolance_ui)
Fix bug smells and add tests!
Closes #180
=> cicd: Added Sonar Cloud to the pipeline for code quality scans

README.md, quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/ProjectServiceImpl.java
Prevents updating with empty fields (title/desc/category/price). Returns 400 Bad Request. 
Closes #178
=> bugfix: Validate empty strings in project update

quolance-ui/package-lock.json, quolance-ui/package.json, quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/setting/components/ChangePassword.tsx, quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/setting/components/DeleteAccount.tsx, quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/setting/components/PasswordStrengthBar.tsx, quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/setting/components/PersonalInfo.tsx, quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/setting/page.tsx, quolance-ui/zxcvbn.d.ts
This is for  task #122 which is linked to story #121 
The setting page is currently only accessible through url at /setting for authenticated accounts.
In this page you can view personal information like first name, last name and email address. 
In this page you can change the current password by inputing current password, new password and confirmation password. The appropriate error messages will display below each input. There are error messages for the following
- Empty fields
- Current password not being correct
- New password having less than 8 characters
- Confirm password not equal to new password
- The new password is of correct length but format incorrect ( missing either capital letter, lower case letter or digit)
In this page there is a button to delete account which is not yet …
=> feat: Make UI for settings page for #122

quolance-api/src/main/java/com/quolance/quolance_api/jobs/handlers/SendTempPasswordEmailJobHandler.java, quolance-api/src/main/java/com/quolance/quolance_api/jobs/handlers/SendWelcomeEmailJobHandler.java, quolance-api/src/main/java/com/quolance/quolance_api/services/auth/impl/EmailServiceImpl.java, quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/UserServiceImpl.java
When processing welcome emails via background job, the application was throwing a "User not found" exception. This occurred because the job was being executed before the user creation transaction was fully committed to the database.
- Implemented 1-second scheduling delay for the welcome email job to allow user creation transaction to complete
- Added proper error handling and return early logic for null verification codes
- Cleaned up exception message format for consistency
Closes #200
=> bugfix: Ensure Welcome Email Job Waits for User Transaction Completion for #200

quolance-api/src/test/java/com/quolance/quolance_api/integration/AdminControllerIntegrationTest.java, quolance-api/src/test/java/com/quolance/quolance_api/integration/FreelancerControllerIntegrationTest.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/ClientControllerUnitTest.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/FreelancerControllerUnitTest.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/PublicControllerUnitTest.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/AdminWorkflowServiceUnitTest.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/ClientWorkflowServiceUnitTest.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/FreelancerWorkflowServiceUnitTest.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/ApplicationServiceUnitTest.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/ProjectServiceUnitTest.java
This PR addresses the uncommented and outdated tests for the `FreelancerController`, `ClientController`,`PublicController` and their corresponding ServiceTest Classes updating them to make them work with the recently modified methods and pagination logic. 
- Uncommented and updated tests for methods impacted by pagination.
- Refactored unit and integration tests to match the updated method signatures in:
- **FreelancerController** 
- **ClientController**
- **PublicController** 
- Adjusted other service tests for methods using pagination.
The updated tests now validate the following:
- Pagination parameters such as page number, size, and sorting.
- Correct interaction between controllers, services, and repositories for paginated results.
- Proper filtering and business logic applied to …
=> test: Fixed Commented Tests to work for newly implemented pagination methods

QuolanceAPI.postman_collection.json, quolance-api/src/main/java/com/quolance/quolance_api/controllers/ClientController.java, quolance-api/src/main/java/com/quolance/quolance_api/dtos/profile/FreelancerProfileFilterDto.java, quolance-api/src/main/java/com/quolance/quolance_api/repositories/UserRepository.java, quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/ClientWorkflowService.java, quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/ClientWorkflowServiceImpl.java, quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/UserService.java, quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/UserServiceImpl.java
This PR implements a new endpoint in the `ClientController` to allow clients to retrieve a catalog of freelancer profiles. The catalog supports filtering by  `experienceLevel`, `availability`, and `skills`.  
- Added a new endpoint in `ClientController` to retrieve freelancer catalogs.  
- Implemented filtering logic in the service layer to support dynamic queries based on the provided filters (`experienceLevel`, `availability`, and `skills`).  
- Updated repository methods to accommodate query parameters for filtering freelancer profiles.  
- **ClientController**: `api/client/freelancers/all`  
- `experienceLevel`: Filter freelancers by their experience level (e.g., JUNIOR, INTERMEDIATE, EXPERT).  
- `availability`: Filter by freelancer availability status.  
- `skills`: Filter by …
=> feat: add freelancer catalog for client for #268

quolance-api/src/test/java/com/quolance/quolance_api/integration/ClientControllerIntegrationTest.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/AdminControllerUnitTest.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/AuthControllerUnitTest.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/ClientControllerUnitTest.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/FreelancerControllerUnitTest.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/PendingControllerUnitTest.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/PublicControllerUnitTest.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/jobs/SendResetPasswordEmailUnitTest.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/jobs/SendTempPasswordEmailUnitTest.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/jobs/SendWelcomeEmailUnitTest.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/ApplicationProcessWorkflowUnitTest.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/ClientWorkflowServiceUnitTest.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/ApplicationServiceUnitTest.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/FileServiceUnitTest.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/ProjectServiceUnitTest.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/UserServiceUnitTest.java
This PR slightly improves test coverage across the application by add unit tests to cover additional scenarios and adding new tests for the recently implemented freelancer catalog feature. Both unit and integration tests have been introduced to ensure reliability and accuracy.  
- Added a few extra unit tests to cover previously uncovered scenarios.  
- Added unit tests for the `getFreelancerCatalog` functionality in the `ClientController` and `ClientWorkflowService`.  
- Added integration tests to validate end-to-end behavior of the freelancer catalog retrieval feature.  
- Unit test: Verifies the service layer correctly handles filtering parameters (`experienceLevel`, `availability`, `skills`).  
- Integration test: Ensures API endpoint returns the correct filtered data for request: …
=> test: Add Unit tests for better coverage and Tests for Freelancer Catalog

quolance-ui/package-lock.json, quolance-ui/package.json, quolance-ui/src/api/blog-api.ts, quolance-ui/src/components/ui/blog/PostCard.tsx, quolance-ui/src/components/ui/blog/PostReaction.tsx
This PR fully integrates the reaction functionality for blog posts with the backend, enabling real-time updates and accurate reflection of user reactions. Users can now react to posts with various reactions such as "Like," "Love," "Laugh," "Shocked," "Sad," and "Angry." The backend ensures that reactions are tied to authenticated users and stored appropriately, while the frontend dynamically updates reaction counts and icons based on the data fetched from the backend.
---
1. **Backend Integration**
- **Fetching Reactions**: 
- Added the `useGetReactionsByPostId` hook to fetch reactions for each blog post from the `/api/blog-posts/reactions/post/{postId}` endpoint.
- **Posting Reactions**: 
- Added the `useReactToPost` hook to handle user reactions via the `/api/blog-posts/reactions/post` …
=> feat: #249 Make UI for leaving reactions on a post

quolance-api/src/main/java/com/quolance/quolance_api/entities/User.java, quolance-api/src/test/java/com/quolance/quolance_api/integration/AuthControllerIntegrationTest.java, quolance-api/src/test/java/com/quolance/quolance_api/integration/BlogCommentControllerIntegrationTest.java, quolance-api/src/test/java/com/quolance/quolance_api/integration/UsersControllerIntegrationTest.java
Added a list of projects field in the user class with a cascade declaration to fix failing integration tests. 
Integration tests were failing because of a foreign key constraint on the table project. Deleting users, without deleting the project repository first was causing problems, as seen in the image:
Closes #304
=> bugfix: #304 Fixed integration tests failing due to foreign key constraints on table "projects"

quolance-api/src/main/java/com/quolance/quolance_api/controllers/blog/BlogCommentController.java, quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/blog/BlogCommentService.java, quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/blog/BlogCommentServiceImpl.java
=> bugfix: #288 Fixed backend bug where users could update or delete comments that are not theirs

QuolanceAPI.postman_collection.json, quolance-api/src/main/java/com/quolance/quolance_api/controllers/FreelancerController.java, quolance-api/src/main/java/com/quolance/quolance_api/dtos/profile/ProfileCompletionCalculator.java, quolance-api/src/main/java/com/quolance/quolance_api/entities/enums/ProfileField.java
This PR adds the backend that calculates the percentage of profile completion for a Freelancers  
- Added `ProfileField` enum and added criteria for percentage
- Added calculator `ProfileCompletionCalculator` to calculate percentatge
- Added corresponding endpoint `/profile/completion` in `FreelancerController`
- The endpoint outputs an Integer value corresponding to percentage
=> feat: #334 Add BE for Profile Completion Progress Bar

infrastructure/docker-compose.yaml, quolance-api/src/main/java/com/quolance/quolance_api/configs/AdminInitializer.java, quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/UserServiceImpl.java, quolance-api/src/test/resources/application-test.yml
- Temporarily removed Profile setting on the AdminInitializer to have an admin generated in production.
- Temporarily set user verification to true without validating email.
Closes #379
=> bugfix: #379 Added temporary fix for users cant verify account in production

quolance-api/src/main/java/com/quolance/quolance_api/configs/FeatureToggleConfig.java, quolance-api/src/main/java/com/quolance/quolance_api/controllers/ClientController.java, quolance-api/src/main/java/com/quolance/quolance_api/dtos/project/ProjectEvaluationResult.java, quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/ClientWorkflowServiceImpl.java, quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/ProjectServiceImpl.java, quolance-api/src/main/java/com/quolance/quolance_api/util/FeatureToggle.java, quolance-api/src/main/resources/toggles.properties, quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/ClientControllerIntegrationTest.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/ClientWorkflowServiceUnitTest.java
- Added a toggle `useAiProjectEvaluation` to activate and deactivate the AI feature to automatically approve/reject projects.
- To enable the AI feature, set the value `feature.toggles.toggles.useAiProjectEvaluation=true` in `toggles.properties`
- For now, we are returning a `ProjectEvaluationResult` object, both when the toggle is on and off. However, when it is off and it behaves as it did previously (ie: when the project was by default to be approved by an admin), we do not need it. Might need to delete this entity, especially if it is not needed in the UI.
Closes #395
=> feat: #395 Added toggle for project evaluation by AI model

quolance-api/src/main/java/com/quolance/quolance_api/configs/ApplicationProperties.java, quolance-api/src/main/java/com/quolance/quolance_api/configs/SecurityConfiguration.java, quolance-api/src/main/java/com/quolance/quolance_api/controllers/UsersController.java, quolance-api/src/main/java/com/quolance/quolance_api/dtos/users/VerifyEmailDto.java, quolance-api/src/main/java/com/quolance/quolance_api/jobs/handlers/SendWelcomeEmailJobHandler.java, quolance-api/src/main/java/com/quolance/quolance_api/repositories/VerificationCodeRepository.java, quolance-api/src/main/java/com/quolance/quolance_api/services/auth/VerificationCodeService.java, quolance-api/src/main/java/com/quolance/quolance_api/services/auth/impl/VerificationCodeServiceImpl.java, quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/UserService.java, quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/UserServiceImpl.java, quolance-api/src/main/resources/application-local.yml, quolance-api/src/main/resources/application.yml, quolance-api/src/main/resources/mail-templates/welcome-email.html, quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/UsersControllerUnitTest.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/jobs/SendWelcomeEmailUnitTest.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/UserServiceUnitTest.java, quolance-ui/src/app/(without-main-layout)/auth/register/components/register-form.tsx, quolance-ui/src/app/(without-main-layout)/auth/verify-email/components/verification-code.tsx, quolance-ui/src/app/(without-main-layout)/auth/verify-email/page.tsx
- Earlier in the project, the verification token that was sent to the user was embedded in the link they receive by email. The link made a direct request to the api. The problem with that was that when we removed the reverse proxy, the request to the backend was always denied, because it was not from a trusted origin.
- To solve this issue, we temporarily set the verification of a user to `true` by default, so that we could continue using the platform while we find a solution.
- Instead of the user verifying the email by clicking on a link, we instead changed it to send a verification code to the email.
- The user needs to type his email and code in the verification page, whose links are available in the email or at the success message upon registration.
- The email that is sent to the …
=> feat: #401 User can verify email by entering a code received by email

quolance-ui/src/components/ui/blog/CommentCard.tsx
The endpoint change in handling paging #327 affected the check on whether a comment was made by the current user. The previous endpoint was returning the userId while the current one returns username. Dead code was removed, and intended code was enabled.
=> bug: #321 delete button not appearing for comments

quolance-api/src/main/java/com/quolance/quolance_api/controllers/FileController.java, quolance-api/src/main/java/com/quolance/quolance_api/repositories/FileRepository.java, quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/FileService.java, quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/FileServiceImpl.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/FileControllerUnitTest.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/FileServiceUnitTest.java
This PR implements file deletion functionality, ensuring files are removed from both Cloudinary and the database. It also includes a quick fix to simplify the `getAllFiles` endpoint response.  
- Implemented file deletion that removes files from **Cloudinary** and **database**.  
- Refactored `getAllFiles` endpoint to be **less cluttered**.  
- Extracts **public ID** from Cloudinary file URLs.  
- Deletes the file from **Cloudinary** using `cloudinary.uploader().destroy()`.  
- Removes the file record from the **database**.  
- Now using PageResponseDto instead of Page. Less Clutter
`DELETE /delete/{fileId}`  
- Deletes the file from **Cloudinary** and **database**.  
**Status:** `200 OK`  
**Status:** `400 Bad Request`  
**Message:** `"File not found in user's uploads"`  
**Status:** …
=> feat: #409 Deletion of Uploaded Photos and Documents

quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/ProjectServiceImpl.java
Fixed a bug where a project was set to REJECTED after the moderation service flags it as not accepted AND needing approval.
Closes #418
=> bugfix: #418 changed rejection after AI evaluation only if manual approval is not needed

quolance-api/src/main/java/com/quolance/quolance_api/dtos/project/ProjectEvaluationResult.java, quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/ClientWorkflowServiceImpl.java, quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/ProjectService.java, quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/ProjectServiceImpl.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/ClientWorkflowServiceUnitTest.java, quolance-ui/src/app/(without-main-layout)/(authenticated-pages)/(client-protected-pages)/post-project/page.tsx, quolance-ui/src/components/ProjectStatusNotification.tsx
- Clients can now see when they create their project if it is approved, rejected or pending.
- They see a modal that lets them view their created project or go to the dashboard.
- If the project is rejected, a reason is provided.
- Added ID field in the creation response to allow navigation to the project in the UI.
- Fixed tests
Closes #430
=> feat: #430 Clients see the status of their project on creation

quolance-api/src/main/java/com/quolance/quolance_api/configs/SecurityConfiguration.java, quolance-api/src/main/java/com/quolance/quolance_api/services/auth/impl/OAuth2LoginSuccessHandlerImpl.java, quolance-api/src/main/resources/application-local.yml, quolance-api/src/main/resources/application.yml
This pull request addresses issue #424 by fixing the 'No AuthenticationProvider found for OAuth2LoginAuthenticationToken' error, enhancing authentication mechanisms, improving debugging, and configuring development environment URLs.
**Detailed Changes:**
- **OAuth2 Authentication Provider Configuration:**
- Added explicit bean definition for `OAuth2LoginAuthenticationProvider`, utilizing `DefaultAuthorizationCodeTokenResponseClient` for token responses and `DefaultOAuth2UserService` for user details retrieval.
- Integrated both `DaoAuthenticationProvider` (handling traditional username/password authentication) and the newly added `OAuth2LoginAuthenticationProvider` into the application's `authenticationManager` bean via `ProviderManager`, enabling comprehensive support for authentication …
=> bugfix: #424 Fixed OAuth2 SSO broken due to recent changes

quolance-ui/src/api/blog-api.ts, quolance-ui/src/components/ui/blog/BlogContainer.tsx, quolance-ui/src/components/ui/blog/CreatePostForm.tsx, quolance-ui/src/components/ui/blog/CreatePostModal.tsx, quolance-ui/src/components/ui/blog/PostCard.tsx
This PR introduces **tag selection** during post creation and **tag display** on blog posts. Users can now choose multiple tags when creating a post. Additionally, blog posts now display their associated tag.
---
- Integrated **dropdown menu** for selecting tags when creating a post.
- Ensured **multiple tag selection** is possible.
- Prevented duplicate selections.
- Added the ability to **remove selected tags** before submitting.  
- Updated `PostCard` component to **display tags** under the post title.
---
- Fetch **available tags dynamically** from the backend instead of using a static list.
- Allow **tag-based filtering** of blog posts and tag-based **search functionality**.
---
---
✅ Closes #318
=> feat: #318 Added tags on blog posts upon creation

quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/ClientWorkflowServiceImpl.java
This PR addresses the bug that allowed clients to view other user's projects on their dashboard.
- Added an ID check before retrieving projects.
=> bugfix: #440 Clients see in their dashboards other client projects

quolance-api/src/main/java/com/quolance/quolance_api/dtos/profile/FreelancerProfileDto.java
Handles bug where username is null in Client getAllFreelancers
- Added `username` in fromEntity
=> bugfix: #444 Username null in Client getAllFreelancers

quolance-ui/src/components/ui/blog/CommentCard.tsx, quolance-ui/src/components/ui/blog/PostCard.tsx, quolance-ui/src/components/ui/blog/UserSummary.tsx
=> bugfix: #477 fixed profile pictures' shape for both blog posts and comments

quolance-ui/src/api/blog-api.ts, quolance-ui/src/components/ui/blog/BlogContainer.tsx, quolance-ui/src/components/ui/blog/CommentCard.tsx, quolance-ui/src/components/ui/blog/CreatePostForm.tsx, quolance-ui/src/components/ui/blog/PostCard.tsx
This PR introduces editing capabilities for both blog posts and comments, allowing users to seamlessly update their content. The editing functionality is now integrated into the UI with real-time updates.
---
- **Edit Blog Posts Directly from the UI**
- Users can now click **"Edit"** on their own posts, opening a modal with prefilled data.
- Implemented **"Save" and "Cancel"** options to either update or discard changes.
- **Updated `CreatePostForm.tsx` to Support Editing**
- Added `initialData` prop to populate fields when editing.
- Ensured the form differentiates between **creating a new post and updating an existing one**.
- Introduced conditional logic to send a **PUT request for updates** instead of a POST.
- **Enhanced `BlogContainer.tsx` to Handle Updates**
- Integrated …
=> feat: #439 Made UI for editing a comment post

quolance-api/src/test/resources/logback-test.xml
Fixes all the warning logs that appear when running tests that use Exceptions in Services.
- Added `logback-test-xml` which suppresses logs when running tests for Services.
=> bugfix: #362 Fix Log Errors in Exception Tests for Services

quolance-ui/src/components/ui/blog/BlogContainer.tsx
There was just a small problem in ```CreatePostForm``` related to how we were destructuring ```user id``` when passing its data into ```handleFormSubmit()```.
closes #495
=> bugfix: #495 Fixed bug where clients could not create blog posts

quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/components/update-password-and-role-form.tsx, quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/setting/components/ChangePassword.tsx, quolance-ui/src/app/(without-main-layout)/auth/register/components/register-form.tsx
This PR unifies and enhances the password validation experience across the application. The validation logic and UI are now consistent in the following flows:
- Regular registration
- Google OAuth onboarding (temporary password update)
- Password change from the user profile settings
- Reused `PasswordRequirements` component in all password entry forms:
- Applied to:
- `UpdatePendingUserForm.tsx` (OAuth temporary password update)
- `ChangePassword.tsx` (Profile > Change Password)
- Reused `PasswordStrengthBar` component originally used for profile setting:
- Applied in:
- Registration form
- Google OAuth password update
- Unified password mismatch and invalid pattern messages
Set Password upon registering through Google oAuth
Change Password through Settings
Set Password upon regular …
=> feat: #522 Made Password Validation Consistent Across All User Flows

quolance-api/src/main/java/com/quolance/quolance_api/dtos/blog/BlogPostResponseDto.java, quolance-api/src/main/java/com/quolance/quolance_api/entities/blog/BlogPost.java, quolance-api/src/main/java/com/quolance/quolance_api/repositories/blog/BlogPostRepository.java, quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/blog/BlogPostServiceImpl.java, quolance-api/src/test/java/com/quolance/quolance_api/helpers/integration/EntityCreationHelper.java
This PR enhances the blog post functionality. Blog posts are now sorted by their most recent updates rather than their creation date, allowing the system to display the most recently modified content first.
- Changed sorting logic in the `getPaginatedBlogPosts` method to order by `lastModified` in descending order.
- Replaced previous behavior of sorting by `creationDate` ascending.
- Updated `BlogPostResponseDto` to include the `lastModified` field.
- Ensured `dateCreated`, `lastModified`, `isReported`, and `isResolved` are set when creating BlogPost test entities
- Fixes failing integration tests due to NOT NULL constraint violations
Closes #527
=> feat: #527 Updated post ordering

quolance-ui/src/app/(without-main-layout)/auth/register/components/register-form.tsx
The bug prevented users from verifying their email using the redirection page. They had to click the link in their email.
closes #553
=> bug: #553 Fixed bug where email variable in URL for email verification is undefined

quolance-ui/src/components/ui/blog/PostCard.tsx
This PR fixes an issue where the "Read More" button was not appearing on blog posts in the production build.
Replaced conditional styling class with conditional rendering of `<div>`
Closes #549
=> bugfix: #549 read more button doesn't appear on blogposts in production

quolance-ui/src/components/ui/blog/PostCard.tsx
This PR improves the blog post card layout on smaller screens by adjusting flex behaviour, ensuring a cleaner and more readable stacked layout on mobile while preserving the side-by-side layout on larger screens.
- Switched to responsive flex behaviour (`flex-col` on smaller screens, `flex-row` on larger screens)
- Improved spacing between text and image
Larger screen layout
Smaller screen layout
Closes #551
=> bugfix: #551 Fixed Blog posts text appears compressed on mobile devices

quolance-ui/src/components/ui/blog/PostCard.tsx, quolance-ui/src/components/ui/blog/UserSummary.tsx
This PR addresses minor UI inconsistencies and missing elements identified in **BUG #562** to improve the overall visual consistency and functionality of the blog and user experience.
- Enlarged profile picture for better clarity and visibility.
- Added a clickable link to view the user's full public profile.
- Capped the user bio to six lines to prevent layout overflow with long bios.
- Resized the image preview stack for better visibility and aesthetic balance.
- Replaced the fullscreen viewer close (X), previous (<), and next (>) characters with more reliable and properly aligned alternatives.
- Updated hover effects for fullscreen viewer controls to improve usability and consistency.
- Adjusted the background colour of the image index at the bottom of the fullscreen viewer for better …
=> bugfix: #562 minor UI defects and missing elements

quolance-api/src/main/java/com/quolance/quolance_api/dtos/blog/BlogPostUpdateDto.java, quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/blog/BlogPostServiceImpl.java, quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/BlogControllerUnitTest.java, quolance-ui/src/api/blog-api.ts, quolance-ui/src/components/ui/blog/BlogContainer.tsx, quolance-ui/src/components/ui/blog/CreatePostForm.tsx
This PR implements full support for editing blog post title, content, and tags on both the backend and frontend. Users can now edit their posts directly from the UI.
- **Enable Tag Updates for Existing Blog Posts**
- The `/api/blog-posts/update` endpoint now supports updating tags in addition to title and content.
- Tags are accepted as multiple `tags` fields in `multipart/form-data`, similar to the create post flow.
- **Updated BlogPostServiceImpl**
- Modified the `updateBlogPost` method to handle tag changes.
- **UI Support for Editing Blog Posts**
- Editing allows modifying the title, content, and tags, but **image updates are hidden** during edit mode.
- A conditional UI ensures the file upload field only appears when creating a new post, not when editing.
- **Updated …
=> feat: #560 added support for tags editing in blog posts

quolance-api/src/main/java/com/quolance/quolance_api/configs/ApplicationProperties.java, quolance-api/src/main/java/com/quolance/quolance_api/entities/User.java, quolance-api/src/main/java/com/quolance/quolance_api/jobs/SendGoogleWelcomeEmailJob.java, quolance-api/src/main/java/com/quolance/quolance_api/jobs/handlers/SendGoogleWelcomeEmailJobHandler.java, quolance-api/src/main/java/com/quolance/quolance_api/services/auth/impl/OAuth2LoginSuccessHandlerImpl.java, quolance-api/src/main/resources/application.yml, quolance-api/src/main/resources/mail-templates/welcome-email-google.html, quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/layout.tsx, quolance-ui/src/app/(without-main-layout)/auth/register/components/register-form.tsx, quolance-ui/src/app/(without-main-layout)/auth/shared/auth-components.tsx, quolance-ui/src/app/api/set-role/route.ts
- Modified the registration process for Google users to address comments made by users. 
- Removed the need for a PENDING role.
- The previous process required users to check their email for a temporary password that was sent to them and then asked them to input it along with a new password, before being able to access the platform. 
- This was a complicated process that made google authentication harder than our custom registration.
- Users also had to choose twice what kind of account they want. Once in the registration page and once in the form where they put the new password.
- Stored the value of the desired role in a cookie and and set the role to the value of that cookie, instead of the previous default PENDING role.
- Added a new email that Google users receive instead of a …
=> feat: #555 Simplified OAuth Google authentication process

quolance-ui/src/api/blog-api.ts, quolance-ui/src/components/ui/blog/CommentCard.tsx, quolance-ui/src/components/ui/blog/CreatePostModal.tsx, quolance-ui/src/components/ui/blog/PostCard.tsx, quolance-ui/src/constants/types/blog-types.ts
- Moved blog-related types and DTOs from `/api/blog-api.tsx` to `constants/types/blog-types.ts` to align with Release 2 structural guidelines.
- Replaced dynamic inline styles for UserSummary positioning with TailwindCSS utility classes.
- Removed inline styles from blog post image stack; used TailwindCSS classes for consistent, maintainable styling.
Closes #566
=> refactor: #566 Refactored blog
